version: '2'

services:
  redis:
    restart: always
    privileged: true
    image: wiggins/redis:4.0.6
    environment:
    - TERM=linux
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/redis-data:/data/redis:Z
