version: '2'

services:
  redis:
    container_name: redis_server
    restart: always
    privileged: true
    network_mode: host
    image: wiggins/redis:latest
    environment:
    #启用自定义配置文件
    #- DEFAULT_CONF=disable
    - TERM=linux
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/redis-data:/data/redis:Z
